### ISSUE TITLE
getting wrong pinyin with 好

### ISSUE THREAD

**Issue by Nickxx86** [Language-Tools/mandarin-cantonese-api#5]
I get the pinyin for 好 wrong. See attached
<img width="964" alt="Screenshot 2021-02-07 at 19 25 37" src="https://user-images.githubusercontent.com/78701826/107157210-c495a480-697a-11eb-9de8-41fe8a0f6cab.png">

**Comment by luc-languagetools** [comment]
好 / hao3 is fixed, improved conversion logic.
