### ISSUE TITLE
API Error in Google Sheet

### ISSUE THREAD

**Issue by mathieuboudreau** [Language-Tools/mandarin-cantonese-api#6]
Hi,

Thank you for your app!

It was working fine before, but now I am getting an API error for all of my Google Sheet cells, see below:

Error
Request failed for https://apiv2.mandarincantonese.com returned code 503. Truncated server response: upstream connect error or disconnect/reset before headers. reset reason: local reset (use muteHttpExceptions option to examine full response) (line 67).

**Comment by lucwastiaux** [comment]
Does this happen consistently, even now ?

**Comment by luc-languagetools** [comment]
I believe the addon should be working reliably for now, but feel free to reopen if you're still having issues.
